defaults:
  - general : general_conf
  - model_params: parameters_conf
  - data_params : data_conf
  - _self_
# this would overwrite the defaults ( remember defaults are the files in the defaul folders )
model_params:
    params:
        dir: info/
        epochs: 10
        batch_size: 64
        dampping: 0.99
        lr: 0.1
        gamma: 0.1
        step: 2
        hidden_layers_dim: [40, 20, 10]
        embbeding_size : 64
    hp:
       dampping: [0.95,0.99] 
       lr: [0.001,0.05]
       gamma: [0.1,0.5]
       embbeding_size: [16,128]

data_params:
    dir: data/ 
    negative_percent: 0.5
    train_percent: 0.7
    train_dataset: "train.pkl"
    test_dataset: "train.pkl"
    validation_dataset: "train.pkl"


